apiVersion: v1
kind: Service
metadata:
  name: {{ include "penpot.fullname" . }}-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "penpot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.exporter.service.type }}
  ports:
    - port: {{ .Values.exporter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "penpot.exporterSelectorLabels" . | nindent 4 }}
