/**
 * Re-export shared types from common.
 * Import exporter types from @penpot-exporter/types.
 */

export type {
  ResizeHandlePosition,
  ShapeType,
  BoolType,
  SelectionRectResult,
  PathContent,
  SvgContent,
  Viewport,
  RendererOptions,
  Point,
  ViewportOptions,
  ViewBox,
  PendingImageCallback,
  SetObjectResult,
  ResolveFontUrlCallback,
  FontInfo,
  FontData,
  ViewportPanModifier,
  ShortcutsConfig,
  CanvasWrapperProps,
  WorkerConfig,
  WorkerTextRectDimensions,
  WorkerConfigurePayload,
  WorkerIndexInitializePayload,
  WorkerIndexUpdatePayload,
  WorkerUpdateTextRectPayload,
  IndexedPage,
  QueryParams,
  SelectionIndex,
  WorkerState,
  WorkerMessage,
  SerializedMessage,
  Line,
  WorkerSendPayload,
  WorkerResponse,
  WorkerClient,
  InitializationState,
} from '@skia-rs-wasm/common'

export {
  ZERO_UUID,
  makeSelrect,
  flattenPageToIndexed,
  uuidToU32,
  uuidToU32Tuple,
  hexToU32ARGB,
  colorToU32ARGB,
  u32ToUUID,
  isSvgContentTree,
  isSvgContentString,
  isSvgContent,
  isColorFill,
  isLinearGradient,
  isRadialGradient,
  isImageFill,
} from '@skia-rs-wasm/common'
