image:
  file: gitpod/Dockerfile

ports:
  - port: 3447
  - port: 3448
  - port: 3449
  - port: 6060
  - port: 9090

tasks:
  #- init: ./manage.sh build-devenv
  #  command: ./manage.sh start-devenv

  - init: cd frontend/ && yarn install
    command: npx shadow-cljs watch main

  - init: cd exporter/ && yarn install
    command: npx shadow-cljs watch main

  - command: cd exporter/ && ./scripts/wait-and-start.sh

  - command: cd backend/ && ./scripts/start-dev

  - command: cd frontend/ && npx gulp --theme=${PENPOT_THEME} watch
