image:
  file: docker/gitpod/Dockerfile

ports:
  # frontend nREPL
  - port: 3447
    onOpen: ignore
    visibility: private
  # frontend shadow server
  - port: 3448
    onOpen: notify
    visibility: private
  - port: 3449
  - port: 6060
  - port: 9090
  # exporter shadow server
  - port: 9630
    onOpen: notify
    visibility: private
  # exporter http server
  - port: 6061
    onOpen: ignore
  # mailhog web interface
  - port: 8025
    onOpen: notify
  # mailhog postfix
  - port: 1025
    onOpen: ignore
  # postgres
  - port: 5432
    onOpen: ignore
  # redis
  - port: 6379
    onOpen: ignore
  # openldap
  - port: 389
    onOpen: ignore

tasks:
  #- init: ./manage.sh build-devenv
  #  command: ./manage.sh start-devenv

  - name: redis
    command: redis-server

  - name: mailhog
    command: MailHog

  - before: yarn --cwd ./frontend/ install
    name: frontend shadow watch
    command: cd ./frontend/ && npx -y shadow-cljs watch main

  - before: yarn --cwd ./exporter/ install
    name: exporter shadow watch
    command: cd ./exporter/ && npx -y shadow-cljs watch main

  - name: exporter web server
    openMode: split-right
    command: cd ./exporter/ && ./scripts/wait-and-start.sh

  - init: psql -f docker/gitpod/files/postgresql_init.sql
    name: backend
    command: cd ./backend/ && ./scripts/start-dev

  - name: gulp
    command: cd ./frontend/ && npx -y gulp --theme=${PENPOT_THEME} watch
