image:
  file: docker/gitpod/Dockerfile

ports:
  - port: 3447
  - port: 3448
  - port: 3449
  - port: 6060
  - port: 9090
  - port: 1080

tasks:
  #- init: ./manage.sh build-devenv
  #  command: ./manage.sh start-devenv

  - init: yarn --cwd ./frontend/ install
    command: cd ./frontend/ && npx -y shadow-cljs watch main

  - init: yarn --cwd ./frontend/ install
    command: cd ./exporter/ && npx -y shadow-cljs watch main

  - init: yarn --cwd ./exporter/ install
    command: cd ./exporter/ && ./scripts/wait-and-start.sh

  - init: psql -f docker/gitpod/files/postgresql_init.sql
    command: cd ./backend/ && ./scripts/start-dev

  - init: yarn --cwd ./frontend/ install
    command: cd ./frontend/ && npx -y gulp --theme=${PENPOT_THEME} watch
