#!/usr/bin/env bash

export JAVA_OPTS=${JAVA_OPTS:-"-Xmx1000m -Xms200m"};
EMSDK_QUIET=1 . /home/emsdk/emsdk_env.sh;

alias l='ls --color -GFlh'
alias rm='rm -r'
alias ls='ls --color -F'
alias lsd='ls -d *(/)'
alias lsf='ls -h *(.)'

# include .bashrc if it exists
if [ -f "$HOME/.bashrc.local" ]; then
    . "$HOME/.bashrc.local"
fi
