#!/bin/sh

export PENPOT_ASSERTS_ENABLED=true

set -ex

if [ ! -e ~/.fixtures-loaded ]; then
    echo "Loading fixtures..."
    clojure -Adev -X:fn-fixtures
    touch ~/.fixtures-loaded
fi

if [ "$1" = "--watch" ]; then
    echo "Start Watch..."

    clojure -A:dev -M -m app.main &
    PID=$!

    npx nodemon \
        --watch src \
        --watch ../common \
        --ext "clj" \
        --signal SIGKILL \
        --exec 'echo "(user/restart)" | nc -N localhost 6062'

    kill -9 $PID
else
    clojure -A:dev -M -m app.main
fi



