#!/usr/bin/env bash

set -ex

export CURRENT_VERSION=$1;
export NODE_ENV=production;

corepack enable;
corepack install || exit 1;
pnpm install || exit 1;
rm -rf target

# Build the application
pnpm run build;

cp pnpm-lock.yaml target/;
cp package.json target/;

cat <<EOF | tee target/setup
#/usr/bin/env bash
set -e;
corepack enable;
corepack install;
pnpm install
pnpx playwright install chromium;
EOF

chmod +x target/setup;

sed -i -re "s/\%version\%/$CURRENT_VERSION/g" ./target/app.js;
