#!/usr/bin/env bash

set -ex

yarn install
rm -rf target

export NODE_ENV=production;

# Build the application
clojure -M:dev:shadow-cljs release main

# Remove source
rm -rf target/app

# Copy package*.json files
cp yarn.lock target/
cp package.json target/
