#!/usr/bin/env bash

if [ "$NODE_ENV" = "production" ];  then
    export _BUILD_MODE="release";
else
    export _BUILD_MODE=${1:-debug};
fi

EMCC_CFLAGS="--no-entry \
    -Os \
    -sASSERTIONS=1 \
    -sALLOW_TABLE_GROWTH=1 \
    -sALLOW_MEMORY_GROWTH=1 \
    -sENVIRONMENT=web \
    -sERROR_ON_UNDEFINED_SYMBOLS=0 \
    -sMAX_WEBGL_VERSION=2 \
    -sMODULARIZE=1 \
    -sEXPORT_NAME=createRustSkiaModule \
    -sEXPORTED_RUNTIME_METHODS=GL,stringToUTF8 \
    -sEXPORT_ES6=1"

EMSDK_QUIET=1 . /usr/local/emsdk/emsdk_env.sh;
. /usr/local/cargo/env

export EM_CACHE="/tmp/emsdk_cache";

_CARGO_PARAMS="--target=wasm32-unknown-emscripten";

if [ "$_BUILD_MODE" = "release" ]; then
    _CARGO_PARAMS="--release $_CARGO_PARAMS"
    EMCC_CFLAGS="-Os $EMCC_CFLAGS"
else
    EMCC_CFLAGS="$EMCC_CFLAGS -sMALLOC=emmalloc-debug"
fi

export EMCC_CFLAGS;
export _CARGO_PARAMS;

export SKIA_BINARIES_URL="https://github.com/penpot/skia-binaries/releases/download/0.81.0-1/skia-binaries-24dee32a277b6c7b5357-wasm32-unknown-emscripten-gl-svg-textlayout-binary-cache.tar.gz"
