#!/usr/bin/env bash

# WASM binaries
export SKIA_BINARIES_WASM_URL="https://github.com/penpot/skia-binaries/releases/download/0.90.0/skia-binaries-da4579b39b75fa2187c5-wasm32-unknown-emscripten-gl-svg-textlayout-binary-cache-webp.tar.gz"

# Linux binaries
export SKIA_BINARIES_LINUX_URL="https://github.com/penpot/skia-binaries/releases/download/0.90.0/skia-binaries-da4579b39b75fa2187c5-x86_64-unknown-linux-gnu-gl-svg-textlayout-binary-cache-webp.tar.gz"
