#!/usr/bin/env bash
set -x

_SCRIPT_DIR=$(dirname $0);
pushd $_SCRIPT_DIR;

. ./_build_env 

cargo build $_CARGO_PARAMS

cp target/wasm32-unknown-emscripten/$_BUILD_MODE/render_wasm.js ../frontend/resources/public/js/
cp target/wasm32-unknown-emscripten/$_BUILD_MODE/render_wasm.wasm ../frontend/resources/public/js/

sed -i "s/render_wasm.wasm/render_wasm.wasm?version=develop/g" ../frontend/resources/public/js/render_wasm.js;

popd
