#!/usr/bin/env bash
set -x

_SCRIPT_DIR=$(dirname $0);
pushd $_SCRIPT_DIR;

export BUILD_TARGET="linux"
. ./_build_env

export CARGO_BUILD_TARGET=${CARGO_BUILD_TARGET:-"x86_64-unknown-linux-gnu"};
export SKIA_BINARIES_URL=${SKIA_BINARIES_URL};

cargo test --bin render_wasm -- --show-output

# Exit with the same status code as cargo test
exit $?

popd
