#!/usr/bin/env bash
set -x

_SCRIPT_DIR=$(dirname $0);
pushd $_SCRIPT_DIR;

. ./_build_env

cargo test  $_CARGO_PARAMS --bin render_wasm -- --show-output

# Exit with the same status code as cargo test
exit $?

popd
