#!/usr/bin/env bash
_SCRIPT_DIR=$(dirname $0);

export SKIA_BINARIES_URL="https://github.com/rust-skia/skia-binaries/releases/download/0.80.0/skia-binaries-9e7d2684a17084095aef-x86_64-unknown-linux-gnu-egl-gl-svg-textlayout-vulkan-wayland-webpd-webpe-x11.tar.gz"

pushd $_SCRIPT_DIR;
cargo watch -x "test --bin render_wasm -- --show-output"
popd
