#!/usr/bin/env bash
_SCRIPT_DIR=$(dirname $0);

export SKIA_BINARIES_URL="https://github.com/penpot/skia-binaries/releases/download/0.93.1/skia-binaries-319323662b1685a112f5-x86_64-unknown-linux-gnu-gl-svg-textlayout-binary-cache-webp.tar.gz"

pushd $_SCRIPT_DIR;
cargo watch -x "test --bin render_wasm -- --show-output"
popd
