FROM ubuntu:26.04
LABEL maintainer="Penpot <docker@penpot.app>"

ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    NODE_VERSION=v24.20.0 \
    PNPM_VERSION=12.5.1 \
    DEBIAN_FRONTEND=noninteractive \
    PATH=/opt/node/bin:$PATH

RUN set -ex; \
    useradd -U -M -u 1001 -s /bin/false -d /opt/penpot penpot; \
    mkdir -p /etc/resolvconf/resolv.conf.d; \
    echo "nameserver 127.0.0.11" > /etc/resolvconf/resolv.conf.d/tail; \
    apt-get -qq update; \
    apt-get -qq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade; \
    apt-get -qqy --no-install-recommends install \
      curl \
      tzdata \
      locales \
      ca-certificates \
    ; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*; \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen; \
    locale-gen; \
    find /usr/share/i18n/locales/ -type f ! -name "en_US" ! -name "POSIX" ! -name "C" -delete;

RUN set -ex; \
    apt-get -qq update; \
    apt-get -qqy --no-install-recommends install \
      fontforge \
      woff-tools \
      woff2 \
      \
      libgomp1 \
      libheif1 \
      libjpeg-turbo8 \
      liblcms2-2 \
      libopenexr-3-1-30 \
      libopenjp2-7 \
      libpng16-16 \
      librsvg2-2 \
      libtiff6 \
      libwebp7 \
      libwebpdemux2 \
      libwebpmux3 \
      libxml2-16 \
      libzip5 \
      libzstd1 \
    ; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*;

RUN set -eux; \
    ARCH="$(dpkg --print-architecture)"; \
    case "${ARCH}" in \
       aarch64|arm64) \
         BINARY_URL="https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-arm64.tar.gz"; \
         PNPM_ARCH='arm64'; \
         PNPM_SHA256='84e1290e82c800acd406b6db27e9650e15db3c2344d12162cc305ea1f942c6ff'; \
         ;; \
       amd64|x86_64) \
         BINARY_URL="https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.gz"; \
         PNPM_ARCH='x64'; \
         PNPM_SHA256='5a397dfb6b3d4b07d3d7769586aeb471048faf04299a492e2808b95a9a1c701f'; \
         ;; \
       *) \
         echo "Unsupported arch: ${ARCH}"; \
         exit 1; \
         ;; \
    esac; \
    curl -LfsSo /tmp/nodejs.tar.gz ${BINARY_URL}; \
    mkdir -p /opt/node; \
    cd /opt/node; \
    tar -xf /tmp/nodejs.tar.gz --strip-components=1; \
    chown -R root /opt/node; \
    rm -rf /tmp/nodejs.tar.gz; \
    PNPM_URL="https://github.com/pnpm/pnpm/releases/download/v${PNPM_VERSION}/pnpm-linux-${PNPM_ARCH}.tar.gz"; \
    curl -LfsSo /tmp/pnpm.tar.gz "${PNPM_URL}"; \
    echo "${PNPM_SHA256} */tmp/pnpm.tar.gz" | sha256sum -c -; \
    tar -xzf /tmp/pnpm.tar.gz -C /opt/node/bin pnpm; \
    chmod 755 /opt/node/bin/pnpm; \
    rm -f /tmp/pnpm.tar.gz; \
    pnpm --version; \
    mkdir -p /opt/penpot; \
    chown -R penpot:penpot /opt/penpot;

ARG BUNDLE_PATH="./bundle-media-processor/"
COPY --chown=penpot:penpot $BUNDLE_PATH /opt/penpot/media-processor/

WORKDIR /opt/penpot/media-processor
USER penpot:penpot

RUN ./setup

CMD ["node", "dist/index.js"]
