#!/usr/bin/env bash
# NOTE: this script should be called from the parent directory to
# properly work

SCRIPT_DIR=$(dirname $0);
URL=${1:-http://localhost:9090}

echo "Preparing bundle for types from $URL"

set -ex

PNPM_VERSION=$(node -p "require('./package.json').packageManager.match(/^pnpm@([^+]+)/)[1]");
PNPM=(npx -y pnpm@"$PNPM_VERSION");

# Ensure clean working directory
rm -rf dist;
rm -rf node_modules;
rm -rf packages/server/dist;
rm -rf packages/server/node_modules;

pushd $SCRIPT_DIR;
set +e
./build-types $URL;
set -e
popd

"${PNPM[@]}" -r --filter "!mcp-plugin" install;
"${PNPM[@]}" -r --filter "mcp-server" run build;

rsync -avr packages/server/dist/ ./dist/;

cp packages/server/package.json ./dist/;
cp pnpm-lock.yaml ./dist/;

touch ./dist/pnpm-workspace.yaml;

cat <<EOF | tee ./dist/setup
#!/usr/bin/env bash
set -e;
PNPM_VERSION=\$(node -p "require('./package.json').packageManager.match(/^pnpm@([^+]+)/)[1]");
npx -y pnpm@"\$PNPM_VERSION" install -P;
EOF

chmod +x ./dist/setup;
