#!/usr/bin/env bash
# NOTE: this script should be called from the parent directory to
# properly work.

export INCLUDE_STORYBOOK=${BUILD_STORYBOOK:-no};
export INCLUDE_WASM=${BUILD_WASM:-yes};
export CURRENT_VERSION=$1;
export BUILD_DATE=$(date -R);
export CURRENT_HASH=${CURRENT_HASH:-$(git rev-parse --short HEAD)};
export EXTRA_PARAMS=$SHADOWCLJS_EXTRA_PARAMS;
export TS=$(date +%s);

# Some cljs reacts on this environment variable for define more
# performant code on macros (example: rumext)
export NODE_ENV=production;

echo "Current path:"
echo $PATH

set -ex

corepack enable;
corepack install;
yarn install || exit 1;

rm -rf target/dist;
rm -rf resources/public;

mkdir -p resources/public;
mkdir -p target/dist;

pushd ../render-wasm;
./build
popd

yarn run build:app:main $EXTRA_PARAMS;
yarn run build:app:libs;
yarn run build:app:assets;

sed -i "s/\.\/render.js/.\/render.js?version=$CURRENT_VERSION/g" resources/public/js/worker/main*.js

rsync -avr resources/public/ target/dist/

if [ "$INCLUDE_STORYBOOK" = "yes" ];  then
    # build storybook
    yarn run build:storybook || exit 1;
    rsync -avr storybook-static/ target/dist/storybook-static;
fi
