#!/bin/sh

DIR=`dirname $0`
LEIN="$DIR/lein"

LEIN_FAST_TRAMPOLINE=y $LEIN trampoline run -m clojure.main scripts/dist-worker.clj

if [ -x "$(command -v gzip)" ]; then
    gzip -9c dist/js/worker.js > dist/js/worker.js.gz
fi

if [ -x "$(command -v bro)" ]; then
    bro --verbose --input dist/js/worker.js --output dist/js/worker.js.br
fi
