#!/usr/bin/env bash

DIR=`dirname $0`
LEIN="$DIR/lein"

RLWRAP=`which rlwrap`
if [ $? != 0 ]; then
    RLWRAP="";
fi

LEIN_FAST_TRAMPOLINE=y $RLWRAP $LEIN trampoline run -m clojure.main scripts/figwheel.clj || exit 1
