#!/usr/bin/env bash

set -ex
corepack enable;
corepack install;

pnpm install;
pnpm run playwright install chromium --with-deps;
pnpm run build:storybook

exec pnpx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
    "pnpx http-server storybook-static --port 6006 --silent" \
    "pnpx wait-on tcp:6006 && pnpm test:storybook"
