// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Copyright (c) KALEIDOS INC

import { type ComponentPropsWithRef, memo } from "react";
import clsx from "clsx";
import styles from "./Icon.module.scss";

// ---------------------------------------------------------------------------
// Icon ID catalogue
// ---------------------------------------------------------------------------

export const iconIds = [
  "absolute",
  "add",
  "align-bottom",
  "align-content-column-around",
  "align-content-column-between",
  "align-content-column-center",
  "align-content-column-end",
  "align-content-column-evenly",
  "align-content-column-start",
  "align-content-column-stretch",
  "align-content-row-around",
  "align-content-row-between",
  "align-content-row-center",
  "align-content-row-end",
  "align-content-row-evenly",
  "align-content-row-start",
  "align-content-row-stretch",
  "align-horizontal-center",
  "align-items-column-center",
  "align-items-column-end",
  "align-items-column-start",
  "align-items-row-center",
  "align-items-row-end",
  "align-items-row-start",
  "align-left",
  "align-right",
  "align-self-column-bottom",
  "align-self-column-center",
  "align-self-column-stretch",
  "align-self-column-top",
  "align-self-row-center",
  "align-self-row-left",
  "align-self-row-right",
  "align-self-row-stretch",
  "align-top",
  "align-vertical-center",
  "arrow",
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "arrow-up-right",
  "asc-sort",
  "at",
  "board",
  "boards-thumbnail",
  "boolean-difference",
  "boolean-exclude",
  "boolean-flatten",
  "boolean-intersection",
  "boolean-union",
  "broken-link",
  "bug",
  "character-a",
  "character-b",
  "character-c",
  "character-d",
  "character-e",
  "character-f",
  "character-g",
  "character-h",
  "character-i",
  "character-j",
  "character-k",
  "character-l",
  "character-m",
  "character-n",
  "character-ntilde",
  "character-o",
  "character-p",
  "character-q",
  "character-r",
  "character-s",
  "character-t",
  "character-u",
  "character-v",
  "character-w",
  "character-x",
  "character-y",
  "character-z",
  "clip-content",
  "clipboard",
  "clock",
  "close",
  "close-small",
  "code",
  "column",
  "column-reverse",
  "comments",
  "component",
  "component-copy",
  "constraint-horizontal",
  "constraint-vertical",
  "corner-bottom",
  "corner-bottom-left",
  "corner-bottom-right",
  "corner-center",
  "corner-radius",
  "corner-top",
  "corner-top-left",
  "corner-top-right",
  "crown",
  "curve",
  "delete",
  "delete-text",
  "desc-sort",
  "detach",
  "detached",
  "distribute-horizontally",
  "distribute-vertical-spacing",
  "document",
  "download",
  "drop",
  "drop-shadow",
  "easing-ease",
  "easing-ease-in",
  "easing-ease-in-out",
  "easing-ease-out",
  "easing-linear",
  "effects",
  "elipse",
  "exit",
  "expand",
  "external-link",
  "eye-off",
  "feedback",
  "fill-content",
  "filter",
  "fixed-width",
  "fit-content",
  "flex",
  "flex-grid",
  "flex-horizontal",
  "flex-vertical",
  "flip-horizontal",
  "flip-vertical",
  "folder",
  "gap-horizontal",
  "gap-vertical",
  "graphics",
  "grid",
  "grid-column",
  "grid-columns",
  "grid-gutter",
  "grid-margin",
  "grid-row",
  "grid-rows",
  "grid-square",
  "group",
  "gutter-horizontal",
  "gutter-vertical",
  "help",
  "hide",
  "history",
  "hsva",
  "hug-content",
  "icon",
  "img",
  "inner-shadow",
  "info",
  "import-export",
  "interaction",
  "join-nodes",
  "justify-content-column-around",
  "justify-content-column-between",
  "justify-content-column-center",
  "justify-content-column-end",
  "justify-content-column-evenly",
  "justify-content-column-start",
  "justify-content-row-around",
  "justify-content-row-between",
  "justify-content-row-center",
  "justify-content-row-end",
  "justify-content-row-evenly",
  "justify-content-row-start",
  "layers",
  "library",
  "locate",
  "lock",
  "margin",
  "margin-bottom",
  "margin-left",
  "margin-left-right",
  "margin-right",
  "margin-top",
  "margin-top-bottom",
  "mask",
  "masked",
  "menu",
  "merge-nodes",
  "move",
  "msg-error",
  "msg-neutral",
  "msg-success",
  "msg-warning",
  "number",
  "open-link",
  "padding-bottom",
  "padding-extended",
  "padding-left",
  "padding-left-right",
  "padding-right",
  "padding-top",
  "padding-top-bottom",
  "path",
  "pentool",
  "percentage",
  "picker",
  "pin",
  "play",
  "puzzle",
  "rectangle",
  "reload",
  "remove",
  "reorder",
  "rgba",
  "rgba-complementary",
  "rotation",
  "row",
  "row-reverse",
  "search",
  "separate-nodes",
  "settings",
  "shown",
  "size-horizontal",
  "size-vertical",
  "snap-nodes",
  "status-alert",
  "status-tick",
  "status-update",
  "status-wrong",
  "stroke-arrow",
  "stroke-center",
  "stroke-circle",
  "stroke-dashed",
  "stroke-diamond",
  "stroke-dotted",
  "stroke-inside",
  "stroke-mixed",
  "stroke-outside",
  "stroke-rectangle",
  "stroke-rounded",
  "stroke-size",
  "stroke-squared",
  "stroke-solid",
  "stroke-triangle",
  "svg",
  "swatches",
  "switch",
  "text",
  "text-align-center",
  "text-align-left",
  "text-align-right",
  "text-auto-height",
  "text-auto-width",
  "text-bottom",
  "text-fixed",
  "text-font-family",
  "text-font-size",
  "text-font-weight",
  "text-justify",
  "text-letterspacing",
  "text-lineheight",
  "text-lowercase",
  "text-ltr",
  "text-middle",
  "text-mixed",
  "text-palette",
  "text-paragraph",
  "text-rtl",
  "text-stroked",
  "text-top",
  "text-typography",
  "text-underlined",
  "text-uppercase",
  "thumbnail",
  "tick",
  "tokens",
  "to-corner",
  "to-curve",
  "tree",
  "unlock",
  "user",
  "variant",
  "vertical-align-items-center",
  "vertical-align-items-end",
  "vertical-align-items-start",
  "view-as-icons",
  "view-as-list",
  "wrap",
] as const;

export type IconId = (typeof iconIds)[number];

// ---------------------------------------------------------------------------
// Icon size constants
// ---------------------------------------------------------------------------

const ICON_SIZE_L = 32;
const ICON_SIZE_M = 16;
const ICON_SIZE_S = 12;

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export interface IconProps extends Omit<
  ComponentPropsWithRef<"svg">,
  "children"
> {
  /** Icon identifier — must be one of the registered icon IDs */
  iconId: IconId;
  /** Visual size variant. Defaults to "m" (16 px). */
  size?: "s" | "m" | "l";
}

function IconInner({ iconId, size = "m", className, ...rest }: IconProps) {
  const sizePx =
    size === "l" ? ICON_SIZE_L : size === "s" ? ICON_SIZE_S : ICON_SIZE_M;

  // For "s" and "m" the SVG viewport is always 16 px; the <use> is offset to
  // centre the smaller glyph inside it.
  const viewportSize = size === "l" ? ICON_SIZE_L : ICON_SIZE_M;
  const offset = size === "s" || size === "m" ? (ICON_SIZE_M - sizePx) / 2 : 0;

  return (
    <svg
      className={clsx(styles.icon, className)}
      width={viewportSize}
      height={viewportSize}
      {...rest}
    >
      <use
        href={`#icon-${iconId}`}
        width={sizePx}
        height={sizePx}
        x={offset}
        y={offset}
      />
    </svg>
  );
}

export const Icon = memo(IconInner);
