import type { PenpotFile } from './penpotFile';
import type { PenpotPage } from './penpotPage';
import type { PenpotBool } from './shapes/boolShape';
import type { CircleShape } from './shapes/circleShape';
import type { PenpotComponent } from './shapes/componentShape';
import type { FrameShape } from './shapes/frameShape';
import type { GroupShape } from './shapes/groupShape';
import type { PathShape } from './shapes/pathShape';
import type { RectShape } from './shapes/rectShape';
import type { TextShape } from './shapes/textShape';
import type { Tokens } from './shapes/tokens';
import type { Color } from './utils/color';
import type { ImageColor } from './utils/imageColor';
import type { Media } from './utils/media';
import type { Typography } from './utils/typography';
import type { Uuid } from './utils/uuid';

export interface PenpotContext {
  currentFileId: Uuid;
  currentFrameId: Uuid;
  currentPageId: Uuid;
  lastId: Uuid;
  addFile(file: PenpotFile): Uuid;
  closeFile(): void;
  addPage(page: PenpotPage): Uuid;
  closePage(): void;
  addBoard(artboard: FrameShape): Uuid;
  closeBoard(): void;
  addGroup(group: GroupShape): Uuid;
  closeGroup(): void;
  addBool(bool: PenpotBool): Uuid;
  addRect(rect: RectShape): Uuid;
  addCircle(circle: CircleShape): Uuid;
  addPath(path: PathShape): Uuid;
  addText(options: TextShape): Uuid;
  addLibraryColor(color: Color): Uuid;
  addLibraryTypography(typography: Typography): Uuid;
  addComponent(component: PenpotComponent): Uuid;
  addFileMedia(media: Media, blob: Blob): Uuid;
  getMediaAsImage(mediaId: Uuid): ImageColor;
  addTokensLib(tokens: Tokens): void;
  addRelation(fileId: Uuid, libraryId: Uuid): void;
  genId(): Uuid;
}
