// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import * as fixture0 from './app/main/ui/components/buttons/primary_button.fixture.js';

export const rendererConfig = {
  "playgroundUrl": "http://localhost:5050",
  "rendererUrl": "http://localhost:3449/#/cosmos"
};

const fixtures = {
  'src/app/main/ui/components/buttons/primary_button.fixture.js': { module: fixture0 }
};

const decorators = {};

export const moduleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
