#!/usr/bin/env bash

set -ex

cljfmt --parallel=true check \
       common/src/ \
       common/test/ \
       frontend/src/ \
       frontend/test/ \
       backend/src/ \
       backend/test/ \
       exporter/src/ \
       library/src;
