name: _TMP TOKENS

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '46 5-20 * * 1-5'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  build-bundle:
    permissions:
      contents: read
    uses: ./.github/workflows/build-bundle.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MATTERMOST_WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
    with:
      gh_ref: "hiru-tokens-in-libs"

  build-docker:
    needs: build-bundle
    permissions:
      contents: read
    uses: ./.github/workflows/build-docker.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      MATTERMOST_WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK }}
      PUB_DOCKER_PASSWORD: ${{ secrets.PUB_DOCKER_PASSWORD }}
      PUB_DOCKER_USERNAME: ${{ secrets.PUB_DOCKER_USERNAME }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
    with:
      gh_ref: "hiru-tokens-in-libs"
