name: DevEnv Docker Image Builder

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push DevEnv Docker image
    environment: release-admins
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PUB_DOCKER_USERNAME }}
          password: ${{ secrets.PUB_DOCKER_PASSWORD }}

      - name: Build and push DevEnv Docker image
        uses: docker/build-push-action@v6
        env:
          DOCKER_IMAGE: 'penpotapp/devenv'
        with:
          context: ./docker/devenv/
          file: ./docker/devenv/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max
