name: _DEVELOP

on:
  workflow_dispatch:
  schedule:
    - cron: '16 5-20 * * 1-5'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-bundle:
    uses: ./.github/workflows/build-bundle.yml
    secrets: inherit
    with:
      gh_ref: "develop"

  build-docker:
    needs: build-bundle
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
    with:
      gh_ref: "develop"

  build-docker-admin-console:
    uses: ./.github/workflows/build-docker-admin-console.yml
    secrets: inherit
    with:
      gh_ref: "develop"
