name: Cleanup Images

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/delete-package-versions@v5
        with: 
            package-name: 'tokens-studio-for-penpot'
            package-type: 'container'
            min-versions-to-keep: 0
            delete-only-untagged-versions: 'true'
