name: Cleanup branches

on:
  delete:
    branches:
     - "*"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: 🍍 Deploy with Gimlet
        uses: gimlet-io/gimlet-artifact-shipper-action@v0.8.3
        env:
            GIMLET_SERVER: ${{ secrets.GIMLET_SERVER }}
            GIMLET_TOKEN: ${{ secrets.GIMLET_TOKEN }}